export const COLUMNAS_POR_DEFECTO = {
  tareas: [
    "fecha",
    "grupoEmpresarial",
    "cliente",
    "nroCliente",
    "cuit",
    "razonsocial",
    "condicionIva",
    "domicilio",
    "estancia",
    "provincia",
    "localidad",
    "ingenieroContacto",
    "coadyudante",
    "retencionHabitual",
    "tarea",
    "hectareas",
    "usdPorHa",
    "totalCobrar",
    "observaciones",
    "facturado",
    "cobrado",
  ],
  facturacion: [
    "numeroFactura",
    "fechaEmision",
    "vencimiento",
    "cliente",
    "cuit",
    "tarea",
    "monto",
    "estado",
  ],
  gastos: [ 
    "cliente",
    "cuit",
    "descripcion",
    "fecha",
    "moneda",
    "monto",
  ],
  clientes: [
    "nombre", 
    "cuit", 
    "email", 
    "telefono", 
    "direccion",
  ],
  administracion: [
    "nombre", 
    "email", 
    "rol", 
    "fechaCreacion",
  ],
};